name: CI KubeNews

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: 02-kube-news/src
          file: 02-kube-news/src/Dockerfile
          push: true
          tags: |
            heliohdd/kube-news-maratona:v${{ github.run_number }}
            heliohdd/kube-news-maratona:latest